package com.yuran.androiddemo.api.bean

/**Created by limengcheng on 2/1/21 5:07 PM.*/
data class UserInfoBean(
    var account: String? = null,
    var addres: String? = null,
    var adminid: Int? = null,
    var avatar: String? = null,
    var birthday: Int? = null,
    var broken_commission: String? = null,
    var brokerage_price: String? = null,
    var card_id: String? = null,
    var commissionCount: String? = null,
    var group_id: Int? = null,
    var integral: String? = null,
    var is_economy: Int? = null,
    var is_promoter: Int? = null,
    var jpush_id: String? = null,
    var level: Int? = null,
    var login_type: String? = null,
    var logout: Int? = null,
    var nickname: String? = null,
    var now_money: String? = null,
    var partner_id: Int? = null,
    var pay_count: Int? = null,
    var personal_center_content: String? = null,
    var personal_center_title: String? = null,
    var phone: String? = null,
    var real_name: String? = null,
    var sign_num: Int? = null,
    var spread_count: Int? = null,
    var spread_time: Int? = null,
    var spread_uid: Int? = null,
    var tx_sign_end_time: Int? = null,
    var tx_user_sign: String? = null,
    var uid: Int? = null,
    var user_type: String? = null
)